### ISSUE TITLE
Support Scala 2.13.0-M5

### ISSUE THREAD

**Issue by raboof** [sullis/jms-testkit#4]
It would be great if we could publish jms-testkit for 2.13.0-M5, to prepare more of the ecosystem to be tested with 2.13

**Comment by ennru** [comment]
We'd like to publish Alpakka for 2.13 now and would need a build of this to get onto it. Alternatively, we'd need to remove this library from Alpakka's JMS tests again.

**Comment by sullis** [comment]
I'll fix this today @ennru

**Comment by sullis** [comment]
I published a new version:  0.2.1

It is cross compiled for 2.11, 2.12, and 2.13

It should appear in Maven Central very soon.

**Comment by ennru** [comment]
Great, thank you!
